title: "DataEngine"
author: "Abel Tavares"
description: "Navigating the intersections of data, technology, and strategy in bite-sized insights." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "abelst9@gmail.com"
#twitter_username: "twitteruser"
github_username: "abeltavares"
linkedin_username: "abeltavares"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"


kramdown:
  syntax_highlighter_opts:
    disable: true

header_pages:
  - aboutme.md
  - CV.html
  - archive.html
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections:
      output: false

#gravatar_hash: a0fd5198f11584c137c480c1dcc058d5
code_block_max_height: 500px

home_post_limit: 5

defaults:
  - scope:
      path: ""
      type: post
    values:
      #image: https://0.gravatar.com/avatar/a0fd5198f11584c137c480c1dcc058d5?size=800 # Apply default site image
  - scope:
      path: ""
      type: posts    
    values:
      tags:
        - Other # Add a default tag to all posts
