title: "DataEngine"
author: "Abel Tavares"
description: "Navigating the intersections of data, technology, and strategy in bite-sized insights." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "abelst9@gmail.com"
#twitter_username: "twitteruser"
github_username: "abeltavares"
linkedin_username: "abeltavares"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"


kramdown:
  syntax_highlighter_opts:
    disable: true

header_pages:
  - CV.html
  - archive.html
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      image: https://s.gravatar.com/avatar/2136e716a089f4a3794f4007328c7bfb?s=800 # Apply default site image
    values:
      tags:
        - Other # Add a default tag to all posts
